# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottreyNums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('num_1', models.CharField(max_length=2)),
                ('num_2', models.CharField(max_length=2)),
                ('num_3', models.CharField(max_length=2)),
                ('num_4', models.CharField(max_length=2)),
                ('num_5', models.CharField(max_length=2)),
                ('num_6', models.CharField(max_length=2)),
            ],
        ),
    ]
